---
version: "2.1"

volumes:
  elasticsearch_data:
  percona_data:
  composer_deps:
  npm_deps:

services:

  atom:
    platform: linux/arm64/v8
    build: ..
    env_file: etc/environment
    environment:
      - ATOM_COVERAGE=${ATOM_COVERAGE:-false}
    volumes:
      - composer_deps:/atom/src/vendor/composer
      - npm_deps:/atom/src/node_modules
      - ..:/atom/src:rw

  atom_worker:
    build: ..
    command: worker
    env_file: etc/environment
    environment:
      - ATOM_COVERAGE=${ATOM_COVERAGE:-false}
    depends_on:
      - gearmand
      - percona
    restart: on-failure:5
    volumes:
      - composer_deps:/atom/src/vendor/composer
      - npm_deps:/atom/src/node_modules
      - ..:/atom/src:rw

  nginx:
    platform: linux/arm64/v8
    image: nginx:latest
    volumes:
      - composer_deps:/atom/src/vendor/composer
      - npm_deps:/atom/src/node_modules
      - ..:/atom/src:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "63001:80"

  elasticsearch:
    platform: linux/arm64
    image: webhippie/elasticsearch:6.4
    env_file: etc/environment
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:63002:9200"

  percona:
    platform: linux/arm64/v8
    image: percona/percona-server:8.0.35-aarch64
    env_file: etc/environment
    volumes:
      - percona_data:/var/lib/mysql:rw
      - ./etc/mysql/mysqld.cnf:/etc/my.cnf.d/mysqld.cnf:ro
    ports:
      - "127.0.0.1:63003:3306"

  memcached:
    platform: linux/arm64/v8
    image: memcached
    command: -p 11211 -m 128 -u memcache
    ports:
      - "127.0.0.1:63004:11211"

  gearmand:
    platform: linux/arm64/v8
    image: artefactual/gearmand
    ports:
      - "127.0.0.1:63005:4730"
